### ISSUE TITLE
Problem to run this script 

### ISSUE THREAD

**Issue by Ranveer20** [CheggEng/zabbix-scripts#3]
./zabbixMaintenance.py --url https://XX.XX.XX.XX/zabbix --user ad --password='zab' --hostgroup='webservers' --maintenance
Traceback (most recent call last):
  File "./zabbixMaintenance.py", line 492, in <module>
    main()
  File "./zabbixMaintenance.py", line 89, in main
    zm.maintenanceModeHostgroup( args.hostgroup,args.maintenance_length )
  File "./zabbixMaintenance.py", line 439, in maintenanceModeHostgroup
    _hostgroup = self.getHostGroupByName(hostgroup)
  File "./zabbixMaintenance.py", line 394, in getHostGroupByName
    result = self.zapi.do_request('hostgroup.get',args)
TypeError: do_request() takes exactly 2 arguments (3 given)

**Comment by analogrithems** [comment]
I can't reproduce this.  Are you sure you are using the most current version?

`
wage-slave:zabbix-scripts jdoe$ ./zabbixMaintenance.py --url https://monitor.example.com/zabbix --user jdoe --password='***secret***' --hostgroup='webservers' --maintenance
No matching hostgroup found for 'webservers'
wage-slave:zabbix-scripts jdoe$ ./zabbixMaintenance.py --url https://monitor.example.com/zabbix --user jdoe --password='***secret***' --hostgroup='marketing-web-NotProd' --maintenance
`

**Comment by steevivo** [comment]
Hi,

Can you specify which value for "--maintenance-length" it's in sec ? such as
--maintenance-length 3600 or 7200 etc but if I would like in few days ?
